"""Add gst_applicable to CostItem

Revision ID: 25050cc4bfa0
Revises: 6f15878a5977
Create Date: 2026-08-28 10:36:49.236404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25050cc4bfa0'
"""Add gst_applicable to CostItem

Revision ID: 25050cc4bfa0
Revises: 6f15878a5977
Create Date: 2026-08-28 10:36:49.236404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25050cc4bfa0'
down_revision: Union[str, Sequence[str], None] = '6f15878a5977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_items', sa.Column('gst_applicable', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_items', 'gst_applicable')
    # ### end Alembic commands ###
