"""Add land_inputs and acquisition_cost_items

Revision ID: 6f15878a5977
Revises: 334fb929e32f
Create Date: 2026-08-27 22:38:52.752247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f15878a5977'
down_revision: Union[str, Sequence[str], None] = '334fb929e32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('deposit_due_date', sa.Date(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('site_area', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('site_area_unit', sa.String(length=50), nullable=False),
    sa.Column('current_zoning', sa.String(length=100), nullable=True),
    sa.Column('existing_improvements', sa.Text(), nullable=True),
    sa.Column('planning_notes', sa.Text(), nullable=True),
    sa.Column('development_potential_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_inputs_scenario_id'), 'land_inputs', ['scenario_id'], unique=True)
    op.create_table('acquisition_cost_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('land_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['land_id'], ['land_inputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquisition_cost_items_land_id'), 'acquisition_cost_items', ['land_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acquisition_cost_items_land_id'), table_name='acquisition_cost_items')
    op.drop_table('acquisition_cost_items')
    op.drop_index(op.f('ix_land_inputs_scenario_id'), table_name='land_inputs')
    op.drop_table('land_inputs')
    # ### end Alembic commands ###
